Add basic yew project

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -16,12 +16,23 @@ echo "Formatting check passed."
 
 # Check linting
 echo "Checking linting..."
-if ! cargo clippy
+if ! cargo clippy --no-deps
 then
 	echo "Linting check failed. See above for details."
 	exit 1
 fi
 echo "Linting check passed."
+
+
+# Attempt building
+echo "Checking build..."
+if ! trunk build
+then
+	echo "Build failed. See above for details."
+	exit 1
+fi
+echo "Build check passed."
+
 
 # Check tests
 echo "Checking tests..."
